### ISSUE TITLE
Pre-compiled assets

### ISSUE THREAD

**Issue by Daniel-ltw** [gsamokovarov/rvt#8]
```
2021-04-18 20:56:16.291887 F [2642:puma threadpool 004 debug_exceptions.rb:9] {request_id: a35ffe90-289f-4d1e-bc28-644e5118fbe6, ip: 172.26.0.7, session: 884fce82e303bb6c8335d32386d298f8} Rails -- Exception: ActionView::Template::Error: rvt/application.css
/usr/local/bundle/gems/sprockets-rails-3.2.2/lib/sprockets/rails/helper.rb:372:in `raise_unless_precompiled_asset'
/usr/local/bundle/gems/sprockets-rails-3.2.2/lib/sprockets/rails/helper.rb:349:in `find_debug_asset'
/usr/local/bundle/gems/sprockets-rails-3.2.2/lib/sprockets/rails/helper.rb:230:in `block in lookup_debug_asset'
/usr/local/bundle/gems/sprockets-rails-3.2.2/lib/sprockets/rails/helper.rb:243:in `block in resolve_asset'
/usr/local/bundle/gems/sprockets-rails-3.2.2/lib/sprockets/rails/helper.rb:242:in `each'
/usr/local/bundle/gems/sprockets-rails-3.2.2/lib/sprockets/rails/helper.rb:242:in `detect'
/usr/local/bundle/gems/sprockets-rails-3.2.2/lib/sprockets/rails/helper.rb:242:in `resolve_asset'
/usr/local/bundle/gems/sprockets-rails-3.2.2/lib/sprockets/rails/helper.rb:229:in `lookup_debug_asset'
/usr/local/bundle/gems/sprockets-rails-3.2.2/lib/sprockets/rails/helper.rb:171:in `block in stylesheet_link_tag'
/usr/local/bundle/gems/sprockets-rails-3.2.2/lib/sprockets/rails/helper.rb:170:in `map'
/usr/local/bundle/gems/sprockets-rails-3.2.2/lib/sprockets/rails/helper.rb:170:in `stylesheet_link_tag'
/usr/local/bundle/gems/rvt-1.1.0/app/views/layouts/rvt/application.html.erb:6:in `__usr_local_bundle_gems_rvt______views_layouts_rvt_application_html_erb___3357760447522775154_74000'
```

Is there a better way to handle or deal with this? 
Do I really need to precompile assets just for a single gem dependency?

**Comment by redvex** [comment]
any solution for this one?

**Comment by Daniel-ltw** [comment]
@redvex Have not heard back. Assuming @gsamokovarov have not looked into this.

**Comment by gsamokovarov** [comment]
I'm sorry, folks! I have neglected this gem for quite a while now...

What do you propose here? As this gem stands, it's quite integrated with the good-old asset pipeline. Do you want to inline the assets, so you don't need to precompile them?

**Comment by Daniel-ltw** [comment]
I reckon as a good work around, just do pure static assets as much as possible, so there is no need for the precompile. 

The only issue I have seen in code is the erb css file.
